services:
  buf:
    image: bufbuild/buf:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
    entrypoint: ["buf"]

  protoc:
    image: namely/protoc-all:latest
    working_dir: /workspace
    volumes:
      - ../:/workspace
