events {}

http {
  server {

    listen 80;

    location / {
      proxy_pass http://web:3000;
    }

    location /api {
      proxy_pass http://api:8080;
    }

    location /media {
      proxy_buffering off;
      proxy_pass http://minio:9000;
    }
  }
}
