syntax = "proto3";

package recommendation;

option go_package = "io.github.moughamir/amudia/gen/go/recommendation";
option java_package = "io.github.moughamir.amudia.recommendation";
option csharp_namespace = "Amudia.Recommendation";

import "media/media.proto";
import "common/pagination.proto";

service RecommendationService {
  rpc GetRecommendations(RecommendationsRequest) returns (RecommendationsResponse);
}

message RecommendationsRequest {
  string user_id = 1;
  common.PageRequest page = 2;
}

message RecommendationsResponse {
  repeated media.Media items = 1;
  common.PageInfo page = 2;
}
